webtalk_init -webtalk_dir C:/Users/brunoa/Documents/cr/proj2/lfsr_tb/lfsr_tb/lfsr_tb.sim/sim_1/behav/xsim/xsim.dir/lfsr_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jul 11 14:04:58 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7a669338-3634-4383-90f1-d4458a1c8737" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d43e4ce0dba34f1abea4ec38140c5481" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6348_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3055157264 -regid "" -xml C:/Users/brunoa/Documents/cr/proj2/lfsr_tb/lfsr_tb/lfsr_tb.sim/sim_1/behav/xsim/xsim.dir/lfsr_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/brunoa/Documents/cr/proj2/lfsr_tb/lfsr_tb/lfsr_tb.sim/sim_1/behav/xsim/xsim.dir/lfsr_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/brunoa/Documents/cr/proj2/lfsr_tb/lfsr_tb/lfsr_tb.sim/sim_1/behav/xsim/xsim.dir/lfsr_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
