package communication;

/**
 * Enumerates to indicate to the receiver about the type of messages
 * @author Bruno Aguiar 80177
 * @author David Rocha 84807
 */
public enum MessageType {
    STATUS_OK,
    DP_NO_MORE_PASSENGERS,
    DP_IS_PLANE_BOARDED,
    PLANE_GET_NUMBER,
    RETURN_NO_PASSENGERS,
    RETURN_PLANE_BOARDED,
    RETURN_PLANE_NUMBER,
    HOSTESS_PREPARE_FOR_BOARDING,
    HOSTESS_CHECK_DOCUMENTS,
    HOSTESS_WAIT_FOR_NEXT_PASSENGER,
    HOSTESS_WAIT_FOR_NEXT_FLIGHT,
    HOSTESS_INFORM_PLANE_READY,
    PASSENGER_TRAVEL_AIRPORT,
    PASSENGER_WAIT_QUEUE,
    PASSENGER_SHOW_DOCUMENTS,
    PASSENGER_LEAVE_PLANE,
    PASSENGER_BOARD_PLANE,
    PASSENGER_WAIT_FOR_END,
    PASSENGER_EXIT,
    PILOT_FLY_DESTINATION_POINT,
    PILOT_PARK_TRANSFER_GATE,
    PILOT_INFORM_TAKEOFF,
    PILOT_WAIT_ALL_INBOARD,
    PILOT_ANNOUNCE_ARRIVAL,
    PILOT_FLY_DEPARTURE_POINT,
    REPO_SET_HOSTESS_STATE,
    REPO_SET_PILOT_STATE,
    REPO_SET_PASSENGER_STATE,
    REPO_INCREMENT_NUMBER_QUEUE,
    REPO_DECREMENT_NUMBER_QUEUE,
    REPO_INCREMENT_NUMBER_PLANE,
    REPO_DECREMENT_NUMBER_PLANE,
    REPO_INCREMENT_NUMBER_DESTINATION,
    REPO_INCREMENT_FLIGHT_NUM,
    REPO_LOG_ENTITIES,
    REPO_LOG,
    REPO_LOG_BOARDING,
    REPO_LOG_PASSENGER_CHECK,
    REPO_LOG_DEPARTURE,
    REPO_LOG_ARRIVAL,
    REPO_LOG_RETURN,
    REPO_CLOSE_LOG,
    SERVER_SHUTDOWN
}